// Auto-generated by Il2CppDumper. Do not edit.
// Filtered by parse-class — 147 entries requested.
//
// Field offsets are byte offsets inside the object (instance) or inside
// the class' static_fields block (static). Each field line ends with the
// C# type of that field — the key aid on obfuscated builds.
//
// type_info is 0x0 on this build (IL2CPP v27+ per-image usage tables not parsed).

#pragma once
#include <cstdint>

namespace offsets
{
    inline constexpr uintptr_t il2cpp_handle = 0x0;

    inline constexpr uintptr_t received_data_from_server        = 0x27D3800; // offset

    // BaseEntity  (TypeDefIndex: 354)
    namespace base_entity
    {
        // instance fields
        inline constexpr uintptr_t model                            = 0x1A8; // Model
        inline constexpr uintptr_t flags                            = 0x1B0; // BaseEntity.Flags
    }

    // SkinnedMultiMesh  (TypeDefIndex: 1531)
    namespace skinned_multi_mesh
    {
        // instance fields
        inline constexpr uintptr_t RendererList                     = 0x50; // List<Renderer>  [was %885917d298102537a48ff117c7bc8472084567a8]
        // carried from reference (not derivable from metadata)
        inline constexpr uintptr_t renderer_list                    = 0x58; // offset
    }

    // BaseCombatEntity  (TypeDefIndex: 1848)
    namespace base_combat_entity
    {
        // instance fields
        inline constexpr uintptr_t lifestate                        = 0x298; // BaseCombatEntity.LifeState
        // carried from reference (not derivable from metadata)
        inline constexpr uintptr_t health                           = 0x2A4; // offset
        inline constexpr uintptr_t max_health                       = 0x2A8; // offset
        inline constexpr uintptr_t model                            = 0x1A8; // offset
    }

    // BaseNetworkable  (TypeDefIndex: 2735)
    namespace base_networkable
    {
        inline constexpr uintptr_t type_info      = 0x0;  // TODO: resolve at runtime via type_definition_index
        inline constexpr uintptr_t static_fields  = 0xB8;
        inline constexpr uintptr_t parent_statics = 0x10;
        inline constexpr uintptr_t wrapper_class  = 0x8;
        // carried from reference (not derivable from metadata)
        inline constexpr uintptr_t entities                         = 0x18; // offset
    }

    // WorldItem  (TypeDefIndex: 3430)
    namespace world_item
    {
        // instance fields
        inline constexpr uintptr_t allowPickup                      = 0x1F0; // bool
        inline constexpr uintptr_t item                             = 0x1F8; // %842300975b8c66f30a8b11cb281c7f8308eea718  [was %036598eec7b993e1aa7f7cb15220582664ea7466]
        // carried from reference (not derivable from metadata)
        inline constexpr uintptr_t allow_pickup                     = 0x1E8; // offset
    }

    // PlayerEyes  (TypeDefIndex: 3445)
    namespace player_eyes
    {
        // instance fields
        inline constexpr uintptr_t viewOffset                       = 0x40; // %0edfbcfa14c5dacec4f7dcebe810c7323587cc6e<Vector3>  [was %adec1224a07987d5237c22aa805302eef03c9bc6]
        inline constexpr uintptr_t bodyRotation                     = 0x50; // Quaternion  [was %e1d7fb35c9c3e4c65d9bae742ffcd5704e6c4734]
        // carried from reference (not derivable from metadata)
        inline constexpr uintptr_t view_offset                      = 0x40; // offset
        inline constexpr uintptr_t body_rotation                    = 0x50; // offset
        inline constexpr uintptr_t unk_quaternion                   = 0x6C; // offset
    }

    // Model  (TypeDefIndex: 4973)
    namespace model
    {
        // instance fields
        inline constexpr uintptr_t rootBone                         = 0x28; // Transform
        inline constexpr uintptr_t headBone                         = 0x30; // Transform
        inline constexpr uintptr_t boneTransforms                   = 0x50; // Transform[]
        // carried from reference (not derivable from metadata)
        inline constexpr uintptr_t root_bone                        = 0x28; // offset
        inline constexpr uintptr_t head_bone                        = 0x30; // offset
        inline constexpr uintptr_t bone_transforms                  = 0x50; // offset
    }

    // PlayerInventory  (TypeDefIndex: 5034)
    namespace player_inventory
    {
        // carried from reference (not derivable from metadata)
        inline constexpr uintptr_t container1                       = 0x30; // offset
        inline constexpr uintptr_t container2                       = 0x38; // offset
        inline constexpr uintptr_t container3                       = 0x58; // offset
        inline constexpr uintptr_t main_container                   = container1; // alias
        inline constexpr uintptr_t belt                             = container2; // alias
        inline constexpr uintptr_t wear                             = container3; // alias
    }

    // BasePlayer  (TypeDefIndex: 5761)
    namespace base_player
    {
        // instance fields
        inline constexpr uintptr_t PlayerInventory                  = 0x2E0; // %f37fbc7dfcab79e09d81b6365eb8c8c77764e6ce<PlayerInventory>  [was %02532026d29a3aee754ca1d5c36ea1650ede0369]
        inline constexpr uintptr_t player_model                     = 0x3F0; // PlayerModel  [was %a81ae9e1212f9171caab18b007b555e112e1bd8a]
        inline constexpr uintptr_t modelState                       = 0x478; // %1ecd8a2ae847a7ccaed140bc2ad3ea07ec18e1c4  [was %71b0fd58ff2750a5ecc42d5532a71a1baaa9edc7]
        inline constexpr uintptr_t display_name                     = 0x4A8; // string  [was %0a096636d8216a4f1252ca5de44595d63ad5ec72]
        inline constexpr uintptr_t PlayerEyes                       = 0x4F8; // %f37fbc7dfcab79e09d81b6365eb8c8c77764e6ce<PlayerEyes>  [was %a98a42b5bfc536d8e66ba456f98a91fb16069824]
        inline constexpr uintptr_t currentTeam                      = 0x538; // ulong
        inline constexpr uintptr_t clActiveItem                     = 0x568; // %0edfbcfa14c5dacec4f7dcebe810c7323587cc6e<%d01902b3c69e709006b588284a444fa3349c0090>  [was %c928b0dcec5bddd75df60086a11b6a8387ef5b67]
        inline constexpr uintptr_t playerFlags                      = 0x6B8; // BasePlayer.PlayerFlags
        inline constexpr uintptr_t player_input                     = 0x728; // PlayerInput  [was %e34578bd314a70fe7ba5c8bd846f301a707279cb]
        // carried from reference (not derivable from metadata)
        inline constexpr uintptr_t player_inventory                 = 0x4D0; // offset
        inline constexpr uintptr_t current_team                     = 0x538; // offset
        inline constexpr uintptr_t active_item                      = 0x568; // offset
        inline constexpr uintptr_t cl_active_item                   = active_item; // alias
        inline constexpr uintptr_t player_eyes                      = 0x5F8; // offset
        inline constexpr uintptr_t player_flags                     = 0x6B8; // offset
        inline constexpr uintptr_t base_movement                    = 0x308; // offset
        inline constexpr uintptr_t model_state                      = 0x378; // offset
        inline constexpr uintptr_t steam_id                         = 0x408; // offset
    }

    // PlayerInput  (TypeDefIndex: 5803)
    namespace player_input
    {
        // instance fields
        inline constexpr uintptr_t bodyAngles                       = 0x44; // Vector3  [was %a16d1441743f1e4d14887f726bc4e85f55dd8417]
        // carried from reference (not derivable from metadata)
        inline constexpr uintptr_t body_angles                      = 0x44; // offset
    }

    // RecoilProperties  (TypeDefIndex: 6578)
    namespace recoil_properties
    {
        // instance fields
        inline constexpr uintptr_t clampPitch                       = 0x38; // float
        inline constexpr uintptr_t pitchCurve                       = 0x40; // AnimationCurve
        inline constexpr uintptr_t yawCurve                         = 0x48; // AnimationCurve
        inline constexpr uintptr_t useCurves                        = 0x50; // bool
        inline constexpr uintptr_t newRecoilOverride                = 0x80; // RecoilProperties
        // carried from reference (not derivable from metadata)
        inline constexpr uintptr_t yaw_min                          = 0x18; // offset
        inline constexpr uintptr_t yaw_max                          = 0x1C; // offset
        inline constexpr uintptr_t pitch_min                        = 0x20; // offset
        inline constexpr uintptr_t pitch_max                        = 0x24; // offset
        inline constexpr uintptr_t clamp_pitch                      = 0x38; // offset
        inline constexpr uintptr_t pitch_curve                      = 0x40; // offset
        inline constexpr uintptr_t yaw_curve                        = 0x48; // offset
        inline constexpr uintptr_t use_curves                       = 0x50; // offset
        inline constexpr uintptr_t new_recoil_override              = 0x80; // offset
        inline constexpr uintptr_t time_min                         = 0x28; // offset
        inline constexpr uintptr_t time_max                         = 0x2C; // offset
        inline constexpr uintptr_t ads_scale                        = 0x30; // offset
        inline constexpr uintptr_t move_penalty                     = 0x34; // offset
    }

    // CameraUpdateHook  (TypeDefIndex: 7665)
    namespace camera_update_hook
    {
        // carried from reference (not derivable from metadata)
        inline constexpr uintptr_t action                           = 0x8; // offset
    }

    // BaseProjectile  (TypeDefIndex: 7726)
    namespace base_projectile
    {
        // instance fields
        inline constexpr uintptr_t damageScale                      = 0x374; // float
        inline constexpr uintptr_t automatic                        = 0x380; // bool
        inline constexpr uintptr_t MuzzlePoint                      = 0x3B8; // Transform
        inline constexpr uintptr_t reloadTime                       = 0x3C0; // float
        inline constexpr uintptr_t primaryMagazine                  = 0x3C8; // BaseProjectile.Magazine
        inline constexpr uintptr_t aimSway                          = 0x3E8; // float
        inline constexpr uintptr_t aimSwaySpeed                     = 0x3EC; // float
        inline constexpr uintptr_t recoil                           = 0x3F0; // RecoilProperties
        inline constexpr uintptr_t aimCone                          = 0x400; // float
        inline constexpr uintptr_t hipAimCone                       = 0x404; // float
        inline constexpr uintptr_t numShotsFired                    = 0x43C; // int
        // carried from reference (not derivable from metadata)
        inline constexpr uintptr_t damage_scale                     = 0x374; // offset
        inline constexpr uintptr_t muzzle_point                     = 0x3B8; // offset
        inline constexpr uintptr_t reload_time                      = 0x3C0; // offset
        inline constexpr uintptr_t primary_magazine                 = 0x3C8; // offset
        inline constexpr uintptr_t aim_sway                         = 0x3E8; // offset
        inline constexpr uintptr_t aim_sway_speed                   = 0x3EC; // offset
        inline constexpr uintptr_t aim_cone                         = 0x400; // offset
        inline constexpr uintptr_t hip_aim_cone                     = 0x404; // offset
        inline constexpr uintptr_t num_shots_fired                  = 0x43C; // offset
        inline constexpr uintptr_t projectile_vel_scale             = damage_scale; // alias
    }

    // PlayerModel  (TypeDefIndex: 8223)
    namespace player_model
    {
        // carried from reference (not derivable from metadata)
        inline constexpr uintptr_t velocity                         = 0x28; // offset
        inline constexpr uintptr_t position                         = 0x2F8; // offset
        inline constexpr uintptr_t skinned_mesh_renderer            = 0x448; // offset
        inline constexpr uintptr_t SkinnedMultiMesh                 = 0x448; // offset
    }

    // BaseViewModel  (TypeDefIndex: 8308)
    namespace base_view_model
    {
        // instance fields
        inline constexpr uintptr_t viewmodelType                    = 0x50; // BaseViewModel.ViewmodelType
        inline constexpr uintptr_t MuzzlePoint                      = 0x58; // Transform
        // carried from reference (not derivable from metadata)
        inline constexpr uintptr_t viewmodel_type                   = 0x50; // offset
        inline constexpr uintptr_t muzzle_point                     = 0x58; // offset
        inline constexpr uintptr_t list                             = 0x90; // offset
        inline constexpr uintptr_t animation_events                 = 0xE0; // offset
        inline constexpr uintptr_t viewmodel_lower                  = viewmodel_type; // alias
        inline constexpr uintptr_t viewmodel_bob                    = muzzle_point; // alias
        inline constexpr uintptr_t viewmodel_sway                   = animation_events; // alias
    }

    // ItemDefinition  (TypeDefIndex: 8669)
    namespace item_definition
    {
        // instance fields
        inline constexpr uintptr_t displayName                      = 0x40; // %93cba345c1c7797df4c30850761444134f17242b.Phrase
        inline constexpr uintptr_t category                         = 0x58; // ItemCategory
        inline constexpr uintptr_t ItemModWearable                  = 0x1A8; // ItemModWearable  [was %2c9c824e8d8178888a124a93693ff3bdf148e6ae]
        // carried from reference (not derivable from metadata)
        inline constexpr uintptr_t short_name                       = 0x28; // offset
        inline constexpr uintptr_t item_display_english             = 0x20; // offset
        inline constexpr uintptr_t display_name                     = 0x40; // offset
        inline constexpr uintptr_t item_mod_wearable                = 0x168; // offset
        inline constexpr uintptr_t item_id                          = 0x40; // offset
    }

    // TOD_Sky  (TypeDefIndex: 12555)
    namespace tod_sky
    {
        inline constexpr uintptr_t type_info      = 0x0;  // TODO: resolve at runtime via type_definition_index
        inline constexpr uintptr_t static_fields  = 0xB8;
        // instance fields
        inline constexpr uintptr_t Cycle                            = 0x40; // TOD_CycleParameters
        inline constexpr uintptr_t World                            = 0x48; // TOD_WorldParameters
        inline constexpr uintptr_t Atmosphere                       = 0x50; // TOD_AtmosphereParameters
        inline constexpr uintptr_t Day                              = 0x58; // TOD_DayParameters
        inline constexpr uintptr_t Night                            = 0x60; // TOD_NightParameters
        inline constexpr uintptr_t Sun                              = 0x68; // TOD_SunParameters
        inline constexpr uintptr_t Moon                             = 0x70; // TOD_MoonParameters
        inline constexpr uintptr_t Stars                            = 0x78; // TOD_StarParameters
        inline constexpr uintptr_t Clouds                           = 0x80; // TOD_CloudParameters
        inline constexpr uintptr_t Light                            = 0x88; // TOD_LightParameters
        inline constexpr uintptr_t Fog                              = 0x90; // TOD_FogParameters
        inline constexpr uintptr_t Ambient                          = 0x98; // TOD_AmbientParameters
        inline constexpr uintptr_t Reflection                       = 0xA0; // TOD_ReflectionParameters
        // carried from reference (not derivable from metadata)
        inline constexpr uintptr_t instance                         = 0x0; // offset
    }

    // Action  (TypeDefIndex: 13028)
    namespace action
    {
        // carried from reference (not derivable from metadata)
        inline constexpr uintptr_t invoke_impl                      = 0x0; // offset
        inline constexpr uintptr_t method                           = 0x0; // offset
        inline constexpr uintptr_t method_code                      = 0x0; // offset
    }

    // Camera  (TypeDefIndex: 18280)
    namespace camera
    {
        inline constexpr uintptr_t type_info      = 0x0;  // TODO: resolve at runtime via type_definition_index
        inline constexpr uintptr_t static_fields  = 0xB8;
        // carried from reference (not derivable from metadata)
        inline constexpr uintptr_t camera_object                    = 0x8; // offset
        inline constexpr uintptr_t entity                           = 0x10; // offset
        inline constexpr uintptr_t view_matrix_native               = 0x2FC; // offset
    }

    // SkinnedMeshRenderer  (TypeDefIndex: 18398)
    namespace skinned_mesh_renderer
    {
        // carried from reference (not derivable from metadata)
        inline constexpr uintptr_t list                             = 0x58; // offset
    }

    // Transform  (TypeDefIndex: 18610)
    namespace transform
    {
        // carried from reference (not derivable from metadata)
        inline constexpr uintptr_t visual_state                     = 0x38; // offset
        inline constexpr uintptr_t data_array                       = 0x18; // offset
        inline constexpr uintptr_t index                            = 0x40; // offset
    }

    // (verbatim) list_component_playermodel
    namespace list_component_playermodel
    {
        inline constexpr uintptr_t type_info                        = 0xFCE8520; // offset
        inline constexpr uintptr_t static_fields                    = 0xB8; // offset
        inline constexpr uintptr_t instance                         = 0x8; // offset
        inline constexpr uintptr_t parent                           = 0x10; // offset
        inline constexpr uintptr_t buffer                           = 0x10; // offset
        inline constexpr uintptr_t size                             = 0x18; // offset
    }

    // (verbatim) base_view_model_cctor
    namespace base_view_model_cctor
    {
        inline constexpr uintptr_t type_info                        = 0xFD06708; // offset
    }

    // (verbatim) model_state
    namespace model_state
    {
        inline constexpr uintptr_t flags                            = 0x40; // offset
    }

    // (verbatim) item_container
    namespace item_container
    {
        inline constexpr uintptr_t list                             = 0x28; // offset
        inline constexpr uintptr_t item_list                        = 0x28; // offset
    }

    // (verbatim) item
    namespace item
    {
        inline constexpr uintptr_t item_definition                  = 0x70; // offset
        inline constexpr uintptr_t item_uid                         = 0x40; // offset
        inline constexpr uintptr_t item_uid2                        = 0xA0; // offset
        inline constexpr uintptr_t item_uid3                        = 0xD8; // offset
        inline constexpr uintptr_t item_uid4                        = 0xF0; // offset
        inline constexpr uintptr_t held_entity                      = 0x58; // offset
        inline constexpr uintptr_t held_entity2                     = 0x80; // offset
    }

    // (verbatim) magazine
    namespace magazine
    {
        inline constexpr uintptr_t definition                       = 0x10; // offset
        inline constexpr uintptr_t capacity                         = 0x18; // offset
        inline constexpr uintptr_t contents                         = 0x1C; // offset
        inline constexpr uintptr_t ammo_type                        = 0x20; // offset
    }

    // (verbatim) flint_strike
    namespace flint_strike
    {
        inline constexpr uintptr_t success_frac                     = 0x488; // offset
        inline constexpr uintptr_t strike_recoil                    = 0x490; // offset
        inline constexpr uintptr_t spark_frame                      = 0x498; // offset
    }

    // (verbatim) native
    namespace native
    {
        inline constexpr uintptr_t cached_ptr                       = 0x10; // offset
        inline constexpr uintptr_t game_object                      = 0x30; // offset
        inline constexpr uintptr_t obj_transform                    = 0x8; // offset
    }

    // (verbatim) il2cpp_string
    namespace il2cpp_string
    {
        inline constexpr uintptr_t length                           = 0x10; // offset
        inline constexpr uintptr_t chars                            = 0x14; // offset
    }

    // (verbatim) il2cpp_list
    namespace il2cpp_list
    {
        inline constexpr uintptr_t items                            = 0x10; // offset
        inline constexpr uintptr_t count                            = 0x18; // offset
    }

    // (verbatim) il2cpp_array
    namespace il2cpp_array
    {
        inline constexpr uintptr_t max_length                       = 0x18; // offset
        inline constexpr uintptr_t first_element                    = 0x20; // offset
    }

    // (verbatim) il2cpp_class
    namespace il2cpp_class
    {
        inline constexpr uintptr_t name                             = 0x10; // offset
    }

    // ── Namespace aliases (curated) ──────────────────────────────────
    namespace main_camera = camera;

} // namespace offsets
