// Auto-generated by Il2CppDumper. Do not edit.
// Filtered by parse-class — 720 entries requested.
//
// Field offsets are byte offsets inside the object (instance) or inside
// the class' static_fields block (static). Each field line ends with the
// C# type of that field — the key aid on obfuscated builds.
//
// type_info is 0x0 on this build (IL2CPP v27+ per-image usage tables not parsed).

#pragma once
#include <cstdint>

namespace offsets
{
    inline constexpr uintptr_t il2cpp_handle = 0x0;

    // ─── PE header + IL2CPP runtime API RVAs ───────────────────────────

    namespace GameAssembly
    {
        inline constexpr uintptr_t timestamp = 0x6A6A3C20;
        inline constexpr uintptr_t il2cpp_domain_get                          = 0x846AA0;
        inline constexpr uintptr_t il2cpp_domain_get_assemblies               = 0x846AC0;
        inline constexpr uintptr_t il2cpp_domain_assembly_open                = 0x846AB0;
        inline constexpr uintptr_t il2cpp_assembly_get_image                  = 0x4470;
        inline constexpr uintptr_t il2cpp_image_get_class_count               = 0x2C80;
        inline constexpr uintptr_t il2cpp_image_get_class                     = 0x848F20;
        inline constexpr uintptr_t il2cpp_class_from_name                     = 0x82FF70;
        inline constexpr uintptr_t il2cpp_class_from_il2cpp_type              = 0x845E80;
        inline constexpr uintptr_t il2cpp_class_get_methods                   = 0x8460F0;
        inline constexpr uintptr_t il2cpp_class_get_method_from_name          = 0x846180;
        inline constexpr uintptr_t il2cpp_class_get_fields                    = 0x845EA0;
        inline constexpr uintptr_t il2cpp_class_get_nested_types              = 0x845F20;
        inline constexpr uintptr_t il2cpp_class_get_type                      = 0x71B6B0;
        inline constexpr uintptr_t il2cpp_class_get_name                      = 0xC7B0;
        inline constexpr uintptr_t il2cpp_class_get_namespace                 = 0xC780;
        inline constexpr uintptr_t il2cpp_class_get_parent                    = 0x25F20;
        inline constexpr uintptr_t il2cpp_class_get_image                     = 0x4470;
        inline constexpr uintptr_t il2cpp_class_get_flags                     = 0x8461D0;
        inline constexpr uintptr_t il2cpp_class_get_static_field_data         = 0x2A30;
        inline constexpr uintptr_t il2cpp_type_get_object                     = 0x848C40;
        inline constexpr uintptr_t il2cpp_type_get_class_or_element_class     = 0x848C60;
        inline constexpr uintptr_t il2cpp_type_get_name                       = 0x848C90;
        inline constexpr uintptr_t il2cpp_type_get_attrs                      = 0x848EB0;
        inline constexpr uintptr_t il2cpp_method_get_param_count              = 0x847740;
        inline constexpr uintptr_t il2cpp_method_get_name                     = 0xC780;
        inline constexpr uintptr_t il2cpp_method_get_param                    = 0x847750;
        inline constexpr uintptr_t il2cpp_method_get_return_type              = 0xC7D0;
        inline constexpr uintptr_t il2cpp_method_get_class                    = 0xC7A0;
        inline constexpr uintptr_t il2cpp_method_get_flags                    = 0x847800;
        inline constexpr uintptr_t il2cpp_field_get_offset                    = 0x7D5BF0;
        inline constexpr uintptr_t il2cpp_field_get_type                      = 0x440E40;
        inline constexpr uintptr_t il2cpp_field_get_parent                    = 0xC7B0;
        inline constexpr uintptr_t il2cpp_field_get_name                      = 0x4470;
        inline constexpr uintptr_t il2cpp_field_get_flags                     = 0x846D40;
        inline constexpr uintptr_t il2cpp_field_static_get_value              = 0x846EA0;
        inline constexpr uintptr_t il2cpp_object_get_class                    = 0x4470;
        inline constexpr uintptr_t il2cpp_object_new                          = 0x847B10;
        inline constexpr uintptr_t il2cpp_string_new                          = 0x847C30;
        inline constexpr uintptr_t il2cpp_array_new                           = 0x845D80;
        inline constexpr uintptr_t il2cpp_resolve_icall                       = 0x845D60;
        inline constexpr uintptr_t il2cpp_gchandle_get_target                 = 0x8471D0;
        inline constexpr uintptr_t il2cpp_gchandle_new                        = 0x847180;
        inline constexpr uintptr_t il2cpp_gchandle_free                       = 0x847270;
    }

    inline constexpr uintptr_t domain_get                       = 0x846AA0; // offset
    inline constexpr uintptr_t domain_get_assemblies            = 0x846AC0; // offset
    inline constexpr uintptr_t domain_assembly_open             = 0x846AB0; // offset
    inline constexpr uintptr_t assembly_get_image               = 0x4470; // offset
    inline constexpr uintptr_t class_from_name                  = 0x82FF70; // offset
    inline constexpr uintptr_t image_get_class_count            = 0x2C80; // offset
    inline constexpr uintptr_t image_get_class                  = 0x848F20; // offset
    inline constexpr uintptr_t class_get_methods                = 0x8460F0; // offset
    inline constexpr uintptr_t class_get_method_from_name       = 0x846180; // offset
    inline constexpr uintptr_t class_get_fields                 = 0x845EA0; // offset
    inline constexpr uintptr_t class_get_nested_types           = 0x845F20; // offset
    inline constexpr uintptr_t class_get_type                   = 0x71B6B0; // offset
    inline constexpr uintptr_t class_get_name                   = 0xC7B0; // offset
    inline constexpr uintptr_t class_get_namespace              = 0xC780; // offset
    inline constexpr uintptr_t class_get_parent                 = 0x25F20; // offset
    inline constexpr uintptr_t class_get_image                  = 0x4470; // offset
    inline constexpr uintptr_t class_get_flags                  = 0x8461D0; // offset
    inline constexpr uintptr_t class_get_static_field_data      = 0x2A30; // offset
    inline constexpr uintptr_t class_from_il2cpp_type           = 0x845E80; // offset
    inline constexpr uintptr_t type_get_object                  = 0x848C40; // offset
    inline constexpr uintptr_t type_get_class_or_element_class  = 0x848C60; // offset
    inline constexpr uintptr_t type_get_name                    = 0x848C90; // offset
    inline constexpr uintptr_t type_get_attrs                   = 0x848EB0; // offset
    inline constexpr uintptr_t method_get_param_count           = 0x847740; // offset
    inline constexpr uintptr_t method_get_name                  = 0xC780; // offset
    inline constexpr uintptr_t method_get_param                 = 0x847750; // offset
    inline constexpr uintptr_t method_get_return_type           = 0xC7D0; // offset
    inline constexpr uintptr_t method_get_class                 = 0xC7A0; // offset
    inline constexpr uintptr_t method_get_flags                 = 0x847800; // offset
    inline constexpr uintptr_t field_get_offset                 = 0x7D5BF0; // offset
    inline constexpr uintptr_t field_get_type                   = 0x440E40; // offset
    inline constexpr uintptr_t field_get_parent                 = 0xC7B0; // offset
    inline constexpr uintptr_t field_get_name                   = 0x4470; // offset
    inline constexpr uintptr_t field_get_flags                  = 0x846D40; // offset
    inline constexpr uintptr_t field_static_get_value           = 0x846EA0; // offset
    inline constexpr uintptr_t object_get_class                 = 0x4470; // offset
    inline constexpr uintptr_t object_new                       = 0x847B10; // offset
    inline constexpr uintptr_t resolve_icall                    = 0x845D60; // offset
    inline constexpr uintptr_t gchandle_get_target              = 0x8471D0; // offset
    inline constexpr uintptr_t gchandle_new                     = 0x847180; // offset
    inline constexpr uintptr_t gchandle_free                    = 0x847270; // offset
    inline constexpr uintptr_t array_new                        = 0x845D80; // offset
    inline constexpr uintptr_t string_new                       = 0x847C30; // offset
    inline constexpr uintptr_t il2cpphandle                     = 0x8471D0; // offset
    inline constexpr uintptr_t get_target                       = 0x8471D0; // offset
    inline constexpr uintptr_t BaseNetworkable                  = 0xFBF37A0; // offset
    inline constexpr uintptr_t BaseEntity                       = 0xFBF0198; // offset
    inline constexpr uintptr_t BaseCombatEntity                 = 0xFC3DAD8; // offset
    inline constexpr uintptr_t BasePlayer                       = 0xFCDBAF0; // offset
    inline constexpr uintptr_t BaseNpc                          = 0xFC217E0; // offset
    inline constexpr uintptr_t BaseVehicle                      = 0xFBEF0B0; // offset
    inline constexpr uintptr_t DroppedItemContainer             = 0xFC6F020; // offset
    inline constexpr uintptr_t OreResourceEntity                = 0xFC67928; // offset
    inline constexpr uintptr_t CollectibleEntity                = 0xFC6EEC8; // offset
    inline constexpr uintptr_t BuildingBlock                    = 0xFC53E98; // offset
    inline constexpr uintptr_t BuildingPrivlidge                = 0xFC34510; // offset
    inline constexpr uintptr_t Door                             = 0xFC208C8; // offset
    inline constexpr uintptr_t WorldItem                        = 0xFC6EE88; // offset
    inline constexpr uintptr_t Signage                          = 0xFC9D620; // offset
    inline constexpr uintptr_t MainCamera                       = 0xFC29470; // offset
    inline constexpr uintptr_t PlayerEyes                       = 0xFD80EB8; // offset
    inline constexpr uintptr_t PlayerModel                      = 0xFC74F60; // offset
    inline constexpr uintptr_t TOD_Sky                          = 0xFC45770; // offset
    inline constexpr uintptr_t Item                             = 0xFCA6978; // offset
    inline constexpr uintptr_t ItemId                           = 0xFBEC228; // offset
    inline constexpr uintptr_t ConsoleSystem_Command            = 0xFCDD888; // offset
    inline constexpr uintptr_t PlayerInventory_typenav          = 0xFD80ED8; // offset
    inline constexpr uintptr_t BaseNetworkable_TypeInfo         = 0xFBF37A0; // offset
    inline constexpr uintptr_t BaseEntity_TypeInfo              = 0xFBF0198; // offset
    inline constexpr uintptr_t BasePlayer_TypeInfo              = 0xFCDBAF0; // offset
    inline constexpr uintptr_t BaseNetworkable_TypeDefinitionIndex = 0x2E68; // offset
    inline constexpr uintptr_t BaseEntity_TypeDefinitionIndex   = 0x251B; // offset
    inline constexpr uintptr_t BaseCombatEntity_TypeDefinitionIndex = 0x2AF1; // offset
    inline constexpr uintptr_t BasePlayer_TypeDefinitionIndex   = 0x3A3A; // offset
    inline constexpr uintptr_t BaseNetworkable_TypeInfoSlotIndex = 0xAAF; // offset
    inline constexpr uintptr_t BaseEntity_TypeInfoSlotIndex     = 0x162; // offset
    inline constexpr uintptr_t BaseCombatEntity_TypeInfoSlotIndex = 0x738; // offset
    inline constexpr uintptr_t BasePlayer_TypeInfoSlotIndex     = 0x1681; // offset
    inline constexpr uintptr_t PlayerEyes_TypeInfo              = 0xFD80EB8; // offset
    inline constexpr uintptr_t PlayerInventory_TypeInfo         = 0xFD80ED8; // offset
    inline constexpr uintptr_t PlayerModel_TypeInfo             = 0xFC74F60; // offset
    inline constexpr uintptr_t ModelState_TypeInfo              = 0xFBC9D40; // offset
    inline constexpr uintptr_t PlayerInput_TypeInfo             = 0xFC8D518; // offset
    inline constexpr uintptr_t BaseProjectile_TypeInfo          = 0xFC2D740; // offset
    inline constexpr uintptr_t Projectile_TypeInfo              = 0x100E8A10; // offset
    inline constexpr uintptr_t HitTest_TypeInfo                 = 0xFCB3EC8; // offset
    inline constexpr uintptr_t HeldEntity_TypeInfo              = 0xFBE8C98; // offset
    inline constexpr uintptr_t BaseViewModel_TypeInfo           = 0xFC05F70; // offset
    inline constexpr uintptr_t AutoTurret_TypeInfo              = 0x0; // offset
    inline constexpr uintptr_t PlayerCorpse_TypeInfo            = 0x100E2898; // offset
    inline constexpr uintptr_t LootableCorpse_TypeInfo          = 0x100DFB88; // offset
    inline constexpr uintptr_t GameManager_TypeInfo             = 0x100EA3F0; // offset
    inline constexpr uintptr_t GameManager_Static_TypeInfo      = 0xFC44898; // offset

    // BaseVehicle  (TypeDefIndex: 157)
    namespace base_vehicle
    {
        // instance fields
        inline constexpr uintptr_t ignoreDamageFromOutside          = 0x3D4; // bool
        inline constexpr uintptr_t mountPoints                      = 0x3E0; // List<BaseVehicle.MountPointInfo>
    }

    // TimedExplosive  (TypeDefIndex: 1248)
    namespace timed_explosive
    {
        // instance fields
        inline constexpr uintptr_t timerAmountMin                   = 0x1F0; // float
        inline constexpr uintptr_t timerAmountMax                   = 0x1F4; // float
        inline constexpr uintptr_t minExplosionRadius               = 0x1F8; // float
        inline constexpr uintptr_t explosionRadius                  = 0x1FC; // float
        inline constexpr uintptr_t explodeOnContact                 = 0x200; // bool
        inline constexpr uintptr_t canStick                         = 0x201; // bool
        inline constexpr uintptr_t onlyDamageParent                 = 0x203; // bool
        inline constexpr uintptr_t explosionEffectOffset            = 0x214; // Vector3
        inline constexpr uintptr_t explosionMatchesNormal           = 0x220; // bool
        inline constexpr uintptr_t damageTypes                      = 0x268; // List<DamageTypeEntry>
    }

    // BaseNetworkable  (TypeDefIndex: 2735)
    namespace base_networkable
    {
        inline constexpr uintptr_t static_fields  = 0xB8;
        // instance fields
        inline constexpr uintptr_t prefabID                         = 0x54; // uint
        inline constexpr uintptr_t globalBroadcast                  = 0x58; // bool
        inline constexpr uintptr_t networkRange                     = 0x64; // EntityNetworkRange
    }

    // Model  (TypeDefIndex: 4973)
    namespace model
    {
        // instance fields
        inline constexpr uintptr_t rootBone                         = 0x28; // Transform
        inline constexpr uintptr_t headBone                         = 0x30; // Transform
        inline constexpr uintptr_t eyeBone                          = 0x38; // Transform
        inline constexpr uintptr_t boneTransforms                   = 0x50; // Transform[]
        inline constexpr uintptr_t boneNames                        = 0x58; // string[]
    }

    // Projectile  (TypeDefIndex: 6923)
    namespace projectile
    {
        // instance fields
        inline constexpr uintptr_t initialVelocity                  = 0x28; // Vector3
        inline constexpr uintptr_t drag                             = 0x34; // float
        inline constexpr uintptr_t gravityModifier                  = 0x38; // float
        inline constexpr uintptr_t thickness                        = 0x3C; // float
        inline constexpr uintptr_t initialDistance                  = 0x44; // float
        inline constexpr uintptr_t swimScale                        = 0xF0; // Vector3
        inline constexpr uintptr_t swimSpeed                        = 0xFC; // Vector3
        inline constexpr uintptr_t mod                              = 0x108; // ItemModProjectile  [was %a1676b62a510779bd3c31edff806eca3f0e6adb0]
        inline constexpr uintptr_t owner                            = 0x110; // BasePlayer  [was %29382eb352924bd9c1e738fd8d4f2c7910f0e8c1]
        inline constexpr uintptr_t sourceProjectilePrefab           = 0x128; // Projectile  [was %4ded6a2519dfb38c76a164bdc0c59a25a6b2c227]
        inline constexpr uintptr_t projectileID                     = 0x130; // int  [was %0d12153f1f5b261ceca2ae6b26b276da260f160b]
        inline constexpr uintptr_t launchTime                       = 0x140; // float  [was %bd90abd19f77f2669663eb11cb454c6445f0cc9d]
        inline constexpr uintptr_t currentPosition                  = 0x15C; // Vector3  [was %aa9382dfbe0878ac78ce5a463eb0a3cb3e4260e9]
        inline constexpr uintptr_t currentVelocity                  = 0x168; // Vector3  [was %0dfec824ed04e6c8c0b3884d16c8f134d00f0b28]
        inline constexpr uintptr_t traveledDistance                 = 0x174; // float  [was %9589fa98d5b984963b77542c3b48db540e7cc338]
        inline constexpr uintptr_t traveledTime                     = 0x178; // float  [was %460d16ba7c46d94ac6df592e34612db515b352fb]
        inline constexpr uintptr_t previousTraveledTime             = 0x17C; // float  [was %06eff2496d18d0058cbeffbba903ead8a8cc2754]
        inline constexpr uintptr_t sentPosition                     = 0x180; // Vector3  [was %8a35b576c90b837fb84766ff087bf3f94ffe2b3d]
        inline constexpr uintptr_t maxDistance                      = 0x1A4; // float  [was %dc9d1306e44339bb13587d242511cbc9cc58211e]
        inline constexpr uintptr_t hitTest                          = 0x1D8; // %c333d4d90900f1151de016cfab5209e19c8c2ac5  [was %9b2b6ce7e70afb23620f376830e8c680e8895d8e]
        inline constexpr uintptr_t integrity                        = 0x1F0; // float  [was %23f50784bac98d68de81f0d566d2922988fa9992]
    }

    // ServerProjectile  (TypeDefIndex: 8806)
    namespace server_projectile
    {
        // instance fields
        inline constexpr uintptr_t drag                             = 0x34; // float
        inline constexpr uintptr_t gravityModifier                  = 0x38; // float
        inline constexpr uintptr_t speed                            = 0x3C; // float
        inline constexpr uintptr_t radius                           = 0x5C; // float
    }

    // TOD_AmbientParameters  (TypeDefIndex: 11305)
    namespace tod_ambient_parameters
    {
        // instance fields
        inline constexpr uintptr_t Saturation                       = 0x14; // float
    }

    // TOD_NightParameters  (TypeDefIndex: 11613)
    namespace tod_night_parameters
    {
    }

    // TOD_Sky  (TypeDefIndex: 12555)
    namespace tod_sky
    {
        // instance fields
        inline constexpr uintptr_t Cycle                            = 0x40; // TOD_CycleParameters
        inline constexpr uintptr_t Atmosphere                       = 0x50; // TOD_AtmosphereParameters
        inline constexpr uintptr_t Day                              = 0x58; // TOD_DayParameters
        inline constexpr uintptr_t Night                            = 0x60; // TOD_NightParameters
        inline constexpr uintptr_t Stars                            = 0x78; // TOD_StarParameters
        inline constexpr uintptr_t Clouds                           = 0x80; // TOD_CloudParameters
        inline constexpr uintptr_t Ambient                          = 0x98; // TOD_AmbientParameters
        inline constexpr uintptr_t timeSinceAmbientUpdate           = 0x23C; // float  [was %8064633bf44c5a2644b4c49e7730a1ac78fb34b4]
        inline constexpr uintptr_t timeSinceReflectionUpdate        = 0x240; // float  [was %9120c31a92eb1881e69a2f63ac1a96c5b520fe99]
    }

    // Object  (TypeDefIndex: 13330)
    namespace object
    {
    }

    // Camera  (TypeDefIndex: 18280)
    namespace camera
    {
        inline constexpr uintptr_t static_fields  = 0xB8;
    }

    // (verbatim) GameAssembly
    namespace GameAssembly
    {
        inline constexpr uintptr_t timestamp                        = 0x6A6A3C20; // offset
        inline constexpr uintptr_t type_info_definition_table       = 0x100DB1B8; // offset
        inline constexpr uintptr_t il2cpp_resolve_icall             = 0x845D60; // offset
        inline constexpr uintptr_t il2cpp_array_new                 = 0x845D80; // offset
        inline constexpr uintptr_t il2cpp_assembly_get_image        = 0x4470; // offset
        inline constexpr uintptr_t il2cpp_class_from_name           = 0x82FF70; // offset
        inline constexpr uintptr_t il2cpp_class_get_method_from_name = 0x846180; // offset
        inline constexpr uintptr_t il2cpp_class_get_type            = 0x71B6B0; // offset
        inline constexpr uintptr_t il2cpp_domain_get                = 0x846AA0; // offset
        inline constexpr uintptr_t il2cpp_domain_get_assemblies     = 0x846AC0; // offset
        inline constexpr uintptr_t il2cpp_gchandle_get_target       = 0x8471D0; // offset
        inline constexpr uintptr_t il2cpp_gchandle_new              = 0x847180; // offset
        inline constexpr uintptr_t il2cpp_gchandle_free             = 0x847270; // offset
        inline constexpr uintptr_t il2cpp_method_get_name           = 0xC780; // offset
        inline constexpr uintptr_t il2cpp_object_new                = 0x847B10; // offset
        inline constexpr uintptr_t il2cpp_type_get_object           = 0x848C40; // offset
    }

    // (verbatim) PhysX
    namespace PhysX
    {
        inline constexpr uintptr_t type_info                        = 0xFC1BB40; // offset
        inline constexpr uintptr_t static_fields                    = 0xB8; // offset
    }

    // (verbatim) network
    namespace network
    {
        inline constexpr uintptr_t CLIENT_CONNECTION                = 0x40; // offset
        inline constexpr uintptr_t CLIENT_CONNECTION_WRAPPER        = 0x108; // offset
        inline constexpr uintptr_t RAKNET_HANDLE_IN_WRAPPER         = 0x10; // offset
        inline constexpr uintptr_t CONNECTION_SERVER_GUID           = 0x20; // offset
        inline constexpr uintptr_t CLIENT_GET_LAST_PING_RVA         = 0x7668B10; // offset
    }

    // (verbatim) game_manager
    namespace game_manager
    {
        inline constexpr uintptr_t game_manager                     = 0xFC44898; // offset
        inline constexpr uintptr_t static_fields                    = 0xB8; // offset
    }

    // (verbatim) console_system
    namespace console_system
    {
        inline constexpr uintptr_t find                             = 0x516CDB0; // offset
        inline constexpr uintptr_t get_override                     = 0x60; // offset
        inline constexpr uintptr_t set_override                     = 0x70; // offset
        inline constexpr uintptr_t call                             = 0x18; // offset
    }

    // (verbatim) klass_layout
    namespace klass_layout
    {
        inline constexpr uintptr_t name_ptr                         = 0x10; // offset
        inline constexpr uintptr_t static_fields                    = 0xB8; // offset
    }

    // (verbatim) BasePlayer
    namespace BasePlayer
    {
        inline constexpr uintptr_t clActiveItem                     = 0x568; // offset
        inline constexpr uintptr_t PlayerEyes                       = 0x4F8; // offset
        inline constexpr uintptr_t PlayerInventory                  = 0x2E0; // offset
        inline constexpr uintptr_t current_team                     = 0x538; // offset
        inline constexpr uintptr_t movement                         = 0x6F8; // offset
        inline constexpr uintptr_t player_model                     = 0x3F0; // offset
        inline constexpr uintptr_t playerFlags                      = 0x6B8; // offset
        inline constexpr uintptr_t userID                           = 0x700; // offset
        inline constexpr uintptr_t userIDString                     = 0x420; // offset
        inline constexpr uintptr_t display_name                     = 0x4A8; // offset
        inline constexpr uintptr_t player_input                     = 0x728; // offset
        inline constexpr uintptr_t modelState                       = 0x478; // offset
        inline constexpr uintptr_t mounted                          = 0x5C0; // offset
        inline constexpr uintptr_t Belt                             = 0x528; // offset
        inline constexpr uintptr_t _lookingAt                       = 0x458; // offset
        inline constexpr uintptr_t weaponMoveSpeedScale             = 0x798; // offset
        inline constexpr uintptr_t clothingBlocksAiming             = 0x79C; // offset
        inline constexpr uintptr_t clothingMoveSpeedReduction       = 0x7A0; // offset
        inline constexpr uintptr_t player_rigidbody                 = 0x7B8; // offset
        inline constexpr uintptr_t frozen                           = 0x388; // offset
        inline constexpr uintptr_t currentGesture                   = 0x380; // offset
        inline constexpr uintptr_t lastSentTick                     = 0x390; // offset
    }

    // (verbatim) BaseCombatEntity
    namespace BaseCombatEntity
    {
        inline constexpr uintptr_t skeletonProperties               = 0x220; // offset
        inline constexpr uintptr_t baseProtection                   = 0x228; // offset
        inline constexpr uintptr_t lifestate                        = 0x298; // offset
        inline constexpr uintptr_t markAttackerHostile              = 0x29E; // offset
        inline constexpr uintptr_t model                            = 0x1A8; // offset
        inline constexpr uintptr_t _health                          = 0x2A4; // offset
        inline constexpr uintptr_t _maxHealth                       = 0x2A8; // offset
    }

    // (verbatim) BaseEntity
    namespace BaseEntity
    {
        inline constexpr uintptr_t bounds                           = 0x17C; // offset
        inline constexpr uintptr_t model                            = 0x1A8; // offset
        inline constexpr uintptr_t flags                            = 0x1B0; // offset
        inline constexpr uintptr_t triggers                         = 0x128; // offset
        inline constexpr uintptr_t position                         = 0x0; // offset
        inline constexpr uintptr_t positionLerp                     = 0x158; // offset
    }

    // (verbatim) BaseEntityFlags
    namespace BaseEntityFlags
    {
        inline constexpr uintptr_t Placeholder                      = 0x1; // offset
        inline constexpr uintptr_t On                               = 0x2; // offset
        inline constexpr uintptr_t OnFire                           = 0x4; // offset
        inline constexpr uintptr_t Open                             = 0x8; // offset
        inline constexpr uintptr_t Locked                           = 0x10; // offset
        inline constexpr uintptr_t Debugging                        = 0x20; // offset
        inline constexpr uintptr_t Disabled                         = 0x40; // offset
        inline constexpr uintptr_t Reserved1                        = 0x80; // offset
        inline constexpr uintptr_t Reserved2                        = 0x100; // offset
        inline constexpr uintptr_t Reserved3                        = 0x200; // offset
        inline constexpr uintptr_t Reserved4                        = 0x400; // offset
        inline constexpr uintptr_t Reserved5                        = 0x800; // offset
    }

    // (verbatim) base_player_flags
    namespace base_player_flags
    {
        inline constexpr uintptr_t Unused1                          = 0x1; // offset
        inline constexpr uintptr_t Unused2                          = 0x2; // offset
        inline constexpr uintptr_t IsAdmin                          = 0x4; // offset
        inline constexpr uintptr_t ReceivingSnapshot                = 0x8; // offset
        inline constexpr uintptr_t Sleeping                         = 0x10; // offset
        inline constexpr uintptr_t Spectating                       = 0x20; // offset
        inline constexpr uintptr_t Wounded                          = 0x40; // offset
        inline constexpr uintptr_t IsDeveloper                      = 0x80; // offset
        inline constexpr uintptr_t Connected                        = 0x100; // offset
        inline constexpr uintptr_t ThirdPersonViewmode              = 0x400; // offset
    }

    // (verbatim) ModelState
    namespace ModelState
    {
        inline constexpr uintptr_t flags                            = 0x3C; // offset
        inline constexpr uintptr_t waterLevel                       = 0x58; // offset
        inline constexpr uintptr_t lookDir                          = 0x74; // offset
        inline constexpr uintptr_t Flying                           = 0x40; // offset
        inline constexpr uintptr_t Sleeping                         = 0x8; // offset
        inline constexpr uintptr_t Mounted                          = 0x200; // offset
        inline constexpr uintptr_t OnGround                         = 0x4; // offset
    }

    // (verbatim) ItemContainer
    namespace ItemContainer
    {
        inline constexpr uintptr_t ItemList                         = 0x48; // offset
        inline constexpr uintptr_t flags                            = 0x68; // offset
    }

    // (verbatim) ItemDefinition
    namespace ItemDefinition
    {
        inline constexpr uintptr_t itemid                           = 0x20; // offset
        inline constexpr uintptr_t shortname                        = 0x28; // offset
        inline constexpr uintptr_t displayName                      = 0x40; // offset
        inline constexpr uintptr_t category                         = 0x58; // offset
        inline constexpr uintptr_t stackable                        = 0x78; // offset
        inline constexpr uintptr_t iconSprite                       = 0x50; // offset
        inline constexpr uintptr_t rarity                           = 0x94; // offset
        inline constexpr uintptr_t condition                        = 0xB8; // offset
        inline constexpr uintptr_t ItemModWearable                  = 0x1A8; // offset
    }

    // (verbatim) item
    namespace item
    {
        inline constexpr uintptr_t info                             = 0xB8; // offset
        inline constexpr uintptr_t itemdefinition                   = 0xB8; // offset
        inline constexpr uintptr_t uid                              = 0x20; // offset
        inline constexpr uintptr_t amount                           = 0x18; // offset
        inline constexpr uintptr_t ammoCount                        = 0x38; // offset
        inline constexpr uintptr_t shortname                        = 0x28; // offset
        inline constexpr uintptr_t category                         = 0x58; // offset
        inline constexpr uintptr_t HeldEntity                       = 0x58; // offset
    }

    // (verbatim) AttackEntity
    namespace AttackEntity
    {
        inline constexpr uintptr_t repeatDelay                      = 0x2DC; // offset
        inline constexpr uintptr_t nextAttackTime                   = 0x330; // offset
    }

    // (verbatim) BaseProjectile
    namespace BaseProjectile
    {
        inline constexpr uintptr_t ShotFired                        = 0x5E68300; // offset
        inline constexpr uintptr_t DidAttackClientside              = 0x0; // offset
        inline constexpr uintptr_t SetAmmoCount                     = 0x0; // offset
        inline constexpr uintptr_t BeginCycle                       = 0x5E790D0; // offset
        inline constexpr uintptr_t DoAttack_vtableoff               = 0x0; // offset
        inline constexpr uintptr_t aimCone                          = 0x400; // offset
        inline constexpr uintptr_t hipAimCone                       = 0x404; // offset
        inline constexpr uintptr_t aimSway                          = 0x3E8; // offset
        inline constexpr uintptr_t aimSwaySpeed                     = 0x3EC; // offset
        inline constexpr uintptr_t recoil                           = 0x3F0; // offset
        inline constexpr uintptr_t projectileVelocityScale          = 0x37C; // offset
        inline constexpr uintptr_t automatic                        = 0x380; // offset
        inline constexpr uintptr_t reloadTime                       = 0x3C0; // offset
        inline constexpr uintptr_t primaryMagazine                  = 0x3C8; // offset
        inline constexpr uintptr_t magazine                         = 0x3C8; // offset
        inline constexpr uintptr_t manualCycle                      = 0x41E; // offset
        inline constexpr uintptr_t needsCycle                       = 0x424; // offset
        inline constexpr uintptr_t isReloading                      = 0x46C; // offset
        inline constexpr uintptr_t stancePenalty                    = 0x440; // offset
        inline constexpr uintptr_t aimconePenalty                   = 0x448; // offset
        inline constexpr uintptr_t sightAimConeScale                = 0x45C; // offset
        inline constexpr uintptr_t sight_aim_cone_scale             = 0x45C; // offset
        inline constexpr uintptr_t hipAimConeScale                  = 0x464; // offset
        inline constexpr uintptr_t hip_aim_cone_scale               = 0x464; // offset
        inline constexpr uintptr_t fractionalReload                 = 0x3D0; // offset
        inline constexpr uintptr_t aimconeCurve                     = 0x3F8; // offset
        inline constexpr uintptr_t noAimingWhileCycling             = 0x41D; // offset
        inline constexpr uintptr_t cachedModHash                    = 0x458; // offset
        inline constexpr uintptr_t hipAimConeOffset                 = 0x468; // offset
        inline constexpr uintptr_t sightAimConeOffset               = 0x460; // offset
        inline constexpr uintptr_t aimconePenaltyPerShot            = 0x408; // offset
        inline constexpr uintptr_t aimConePenaltyMax                = 0x40C; // offset
        inline constexpr uintptr_t aimconePenaltyRecoverTime        = 0x410; // offset
        inline constexpr uintptr_t aimconePenaltyRecoverDelay       = 0x414; // offset
        inline constexpr uintptr_t stancePenaltyScale               = 0x418; // offset
        inline constexpr uintptr_t hasADS                           = 0x41C; // offset
        inline constexpr uintptr_t isBurstWeapon                    = 0x427; // offset
        inline constexpr uintptr_t canChangeFireModes               = 0x428; // offset
        inline constexpr uintptr_t internalBurstFireRateScale       = 0x430; // offset
        inline constexpr uintptr_t internalBurstAimConeScale        = 0x434; // offset
    }

    // (verbatim) CompoundBowWeapon
    namespace CompoundBowWeapon
    {
        inline constexpr uintptr_t stringHoldDurationMax            = 0x4C0; // offset
    }

    // (verbatim) PlayerProjectileUpdate
    namespace PlayerProjectileUpdate
    {
        inline constexpr uintptr_t Dispose                          = 0xA9BD8D0; // offset
        inline constexpr uintptr_t _disposed                        = 0x30; // offset
        inline constexpr uintptr_t ShouldPool                       = 0x31; // offset
    }

    // (verbatim) PlayerProjectileAttack
    namespace PlayerProjectileAttack
    {
        inline constexpr uintptr_t hitDistance                      = 0x2C; // offset
        inline constexpr uintptr_t hitVelocity                      = 0x20; // offset
        inline constexpr uintptr_t travelTime                       = 0x10; // offset
    }

    // (verbatim) PlayerAttack
    namespace PlayerAttack
    {
        inline constexpr uintptr_t projectileID                     = 0x20; // offset
    }

    // (verbatim) HitTest
    namespace HitTest
    {
        inline constexpr uintptr_t type                             = 0xA8; // offset
        inline constexpr uintptr_t attackray                        = 0x58; // offset
        inline constexpr uintptr_t rayhit                           = 0x78; // offset
        inline constexpr uintptr_t damageproperties                 = 0xC0; // offset
        inline constexpr uintptr_t gameobject                       = 0xB0; // offset
        inline constexpr uintptr_t collider                         = 0x30; // offset
        inline constexpr uintptr_t ignoredtypes                     = 0x20; // offset
        inline constexpr uintptr_t hittransform                     = 0x40; // offset
        inline constexpr uintptr_t hitpart                          = 0xD4; // offset
        inline constexpr uintptr_t hitmaterial                      = 0x70; // offset
        inline constexpr uintptr_t multihit                         = 0xBD; // offset
        inline constexpr uintptr_t besthit                          = 0xBC; // offset
        inline constexpr uintptr_t hitdistance                      = 0x48; // offset
        inline constexpr uintptr_t radius                           = 0xB8; // offset
        inline constexpr uintptr_t forgivness                       = 0x38; // offset
        inline constexpr uintptr_t didhit                           = 0x2C; // offset
        inline constexpr uintptr_t maxdistance                      = 0x28; // offset
        inline constexpr uintptr_t hitpoint                         = 0xC8; // offset
        inline constexpr uintptr_t hitnormal                        = 0x4C; // offset
        inline constexpr uintptr_t ignoreentity                     = 0x18; // offset
        inline constexpr uintptr_t hitentity                        = 0x10; // offset
    }

    // (verbatim) BaseMelee
    namespace BaseMelee
    {
        inline constexpr uintptr_t damageProperties                 = 0x378; // offset
        inline constexpr uintptr_t maxDistance                      = 0x390; // offset
        inline constexpr uintptr_t attackRadius                     = 0x394; // offset
        inline constexpr uintptr_t blockSprintOnAttack              = 0x399; // offset
        inline constexpr uintptr_t gathering                        = 0x3D0; // offset
        inline constexpr uintptr_t canThrowAsProjectile             = 0x370; // offset
    }

    // (verbatim) ItemModProjectile
    namespace ItemModProjectile
    {
        inline constexpr uintptr_t projectileObject                 = 0x20; // offset
        inline constexpr uintptr_t ammoType                         = 0x30; // offset
        inline constexpr uintptr_t projectileSpread                 = 0x3C; // offset
        inline constexpr uintptr_t projectileVelocity               = 0x40; // offset
        inline constexpr uintptr_t projectileVelocitySpread         = 0x44; // offset
        inline constexpr uintptr_t useCurve                         = 0x48; // offset
        inline constexpr uintptr_t spreadScalar                     = 0x50; // offset
        inline constexpr uintptr_t category                         = 0x68; // offset
    }

    // (verbatim) ProjectileWeaponMod
    namespace ProjectileWeaponMod
    {
        inline constexpr uintptr_t ConditionLossMultiplier          = 0x1F0; // offset
        inline constexpr uintptr_t additiveEffect                   = 0x1F8; // offset
        inline constexpr uintptr_t defaultSilencerEffect            = 0x200; // offset
        inline constexpr uintptr_t isSilencer                       = 0x208; // offset
        inline constexpr uintptr_t silencerType                     = 0x20C; // offset
        inline constexpr uintptr_t repeatDelay                      = 0x210; // offset
        inline constexpr uintptr_t projectileVelocity               = 0x21C; // offset
        inline constexpr uintptr_t projectileDamage                 = 0x228; // offset
        inline constexpr uintptr_t projectileDistance               = 0x234; // offset
        inline constexpr uintptr_t aimsway                          = 0x240; // offset
        inline constexpr uintptr_t aimswaySpeed                     = 0x24C; // offset
        inline constexpr uintptr_t recoil                           = 0x258; // offset
        inline constexpr uintptr_t sightAimCone                     = 0x264; // offset
        inline constexpr uintptr_t hipAimCone                       = 0x270; // offset
        inline constexpr uintptr_t isLight                          = 0x27C; // offset
        inline constexpr uintptr_t isMuzzleBrake                    = 0x27D; // offset
        inline constexpr uintptr_t isMuzzleBoost                    = 0x27E; // offset
        inline constexpr uintptr_t isScope                          = 0x27F; // offset
        inline constexpr uintptr_t zoomAmountDisplayOnly            = 0x280; // offset
        inline constexpr uintptr_t magazineCapacity                 = 0x284; // offset
        inline constexpr uintptr_t needsOnForEffects                = 0x290; // offset
        inline constexpr uintptr_t burstCount                       = 0x294; // offset
        inline constexpr uintptr_t timeBetweenBursts                = 0x298; // offset
        inline constexpr uintptr_t zoomLevels                       = 0x2A0; // offset
        inline constexpr uintptr_t fovChangeEffect                  = 0x2A8; // offset
        inline constexpr uintptr_t allowPings                       = 0x2B0; // offset
    }

    // (verbatim) RecoilProperties
    namespace RecoilProperties
    {
        inline constexpr uintptr_t recoilYawMin                     = 0x18; // offset
        inline constexpr uintptr_t recoilYawMax                     = 0x1C; // offset
        inline constexpr uintptr_t recoilPitchMin                   = 0x20; // offset
        inline constexpr uintptr_t recoilPitchMax                   = 0x24; // offset
        inline constexpr uintptr_t timeToTakeMin                    = 0x28; // offset
        inline constexpr uintptr_t timeToTakeMax                    = 0x2C; // offset
        inline constexpr uintptr_t ADSScale                         = 0x30; // offset
        inline constexpr uintptr_t movementPenalty                  = 0x34; // offset
        inline constexpr uintptr_t clampPitch                       = 0x38; // offset
        inline constexpr uintptr_t pitchCurve                       = 0x40; // offset
        inline constexpr uintptr_t yawCurve                         = 0x48; // offset
        inline constexpr uintptr_t ammoAimconeScaleMultiProjectile  = 0x78; // offset
        inline constexpr uintptr_t ammoAimconeScaleSingleProjectile = 0x7C; // offset
        inline constexpr uintptr_t newRecoilOverride                = 0x80; // offset
        inline constexpr uintptr_t overrideAimconeWithCurve         = 0x5C; // offset
        inline constexpr uintptr_t aimconeProbabilityCurve          = 0x70; // offset
        inline constexpr uintptr_t aimconeCurveScale                = 0x60; // offset
    }

    // (verbatim) FlintStrikeWeapon
    namespace FlintStrikeWeapon
    {
        inline constexpr uintptr_t successFraction                  = 0x4A8; // offset
        inline constexpr uintptr_t strikeRecoil                     = 0x4B0; // offset
        inline constexpr uintptr_t _didSparkThisFrame               = 0x4B8; // offset
    }

    // (verbatim) PlayerEyes
    namespace PlayerEyes
    {
        inline constexpr uintptr_t viewOffset                       = 0x40; // offset
        inline constexpr uintptr_t bodyRotation                     = 0x50; // offset
        inline constexpr uintptr_t worldPosition                    = 0x60; // offset
    }

    // (verbatim) PlayerInput
    namespace PlayerInput
    {
        inline constexpr uintptr_t state                            = 0x28; // offset
        inline constexpr uintptr_t bodyAngles                       = 0x44; // offset
        inline constexpr uintptr_t yaw                              = 0x60; // offset
    }

    // (verbatim) PlayerModel
    namespace PlayerModel
    {
        inline constexpr uintptr_t _multiMesh                       = 0x3B8; // offset
        inline constexpr uintptr_t collision                        = 0xD0; // offset
        inline constexpr uintptr_t fullMask                         = 0x208; // offset
        inline constexpr uintptr_t newVelocity                      = 0x31C; // offset
        inline constexpr uintptr_t isNpc                            = 0x490; // offset
        inline constexpr uintptr_t visibleNullable                  = 0xC4; // offset
    }

    // (verbatim) SkinnedMultiMesh
    namespace SkinnedMultiMesh
    {
        inline constexpr uintptr_t RendererList                     = 0x50; // offset
        inline constexpr uintptr_t Renderers                        = 0x50; // offset
    }

    // (verbatim) chams
    namespace chams
    {
        inline constexpr uintptr_t player_model_multi_mesh          = 0x3B8; // offset
        inline constexpr uintptr_t multi_mesh_renderer_list         = 0x50; // offset
    }

    // (verbatim) PlayerInventory
    namespace PlayerInventory
    {
        inline constexpr uintptr_t loot                             = 0x48; // offset
        inline constexpr uintptr_t containerBelt                    = 0x28; // offset
        inline constexpr uintptr_t containerMain                    = 0x38; // offset
        inline constexpr uintptr_t containerWear                    = 0x58; // offset
    }

    // (verbatim) movement
    namespace movement
    {
        inline constexpr uintptr_t adminCheat                       = 0x20; // offset
        inline constexpr uintptr_t Owner                            = 0x28; // offset
    }

    // (verbatim) PlayerWalkMovement
    namespace PlayerWalkMovement
    {
        inline constexpr uintptr_t zeroFrictionMaterial             = 0x60; // offset
        inline constexpr uintptr_t highFrictionMaterial             = 0x68; // offset
        inline constexpr uintptr_t capsuleHeight                    = 0x70; // offset
        inline constexpr uintptr_t capsuleCenter                    = 0x78; // offset
        inline constexpr uintptr_t capsuleHeightDucked              = 0x80; // offset
        inline constexpr uintptr_t capsuleCenterDucked              = 0x88; // offset
        inline constexpr uintptr_t capsuleRadius                    = 0x90; // offset
        inline constexpr uintptr_t gravityTestRadius                = 0x98; // offset
        inline constexpr uintptr_t gravityMultiplier                = 0xA8; // offset
        inline constexpr uintptr_t gravityMultiplierSwimming        = 0xB0; // offset
        inline constexpr uintptr_t maxAngleWalking                  = 0xB8; // offset
        inline constexpr uintptr_t maxAngleClimbing                 = 0xC0; // offset
        inline constexpr uintptr_t maxAngleSliding                  = 0xC8; // offset
        inline constexpr uintptr_t ladder                           = 0xD8; // offset
        inline constexpr uintptr_t collisionDetectionMode           = 0xE0; // offset
        inline constexpr uintptr_t body                             = 0xE8; // offset
        inline constexpr uintptr_t capsule                          = 0xF0; // offset
        inline constexpr uintptr_t maxVelocity                      = 0xF8; // offset
        inline constexpr uintptr_t groundAngle                      = 0x100; // offset
        inline constexpr uintptr_t groundAngleNew                   = 0x108; // offset
        inline constexpr uintptr_t groundTime                       = 0x110; // offset
        inline constexpr uintptr_t jumpTime                         = 0x118; // offset
        inline constexpr uintptr_t landTime                         = 0x120; // offset
        inline constexpr uintptr_t velocity                         = 0x128; // offset
        inline constexpr uintptr_t groundNormal                     = 0x138; // offset
        inline constexpr uintptr_t groundNormalNew                  = 0x148; // offset
        inline constexpr uintptr_t nextSprintTime                   = 0x198; // offset
        inline constexpr uintptr_t lastSprintTime                   = 0x1A0; // offset
        inline constexpr uintptr_t sprintForced                     = 0x1A8; // offset
        inline constexpr uintptr_t modify                           = 0x1B8; // offset
        inline constexpr uintptr_t grounded                         = 0x1BC; // offset
        inline constexpr uintptr_t wasGrounded                      = 0x1C4; // offset
        inline constexpr uintptr_t climbing                         = 0x1CC; // offset
        inline constexpr uintptr_t wasClimbing                      = 0x1D4; // offset
        inline constexpr uintptr_t sliding                          = 0x1DC; // offset
        inline constexpr uintptr_t wasSliding                       = 0x1E4; // offset
        inline constexpr uintptr_t swimming                         = 0x1EC; // offset
        inline constexpr uintptr_t wasSwimming                      = 0x1F4; // offset
        inline constexpr uintptr_t jumping                          = 0x1FC; // offset
        inline constexpr uintptr_t flying                           = 0x204; // offset
        inline constexpr uintptr_t falling                          = 0x20C; // offset
    }

    // (verbatim) WorldItem
    namespace WorldItem
    {
        inline constexpr uintptr_t item                             = 0x1F8; // offset
        inline constexpr uintptr_t allowPickup                      = 0x1F0; // offset
    }

    // (verbatim) mapview
    namespace mapview
    {
        inline constexpr uintptr_t static_fields_off                = 0xB8; // offset
        inline constexpr uintptr_t RVA_RustWorld                    = 0xFBD1EB8; // offset
        inline constexpr uintptr_t World_Size_off                   = 0x60; // offset
        inline constexpr uintptr_t World_Seed_off                   = 0x20; // offset
        inline constexpr uintptr_t World_Name_off                   = 0x88; // offset
        inline constexpr uintptr_t RVA_MapInterface                 = 0xFCA48F0; // offset
        inline constexpr uintptr_t MI_Instance_off                  = 0x8; // offset
        inline constexpr uintptr_t MI_View_off                      = 0x60; // offset
        inline constexpr uintptr_t MV_mapImage_off                  = 0x20; // offset
        inline constexpr uintptr_t MV_scrollRect_off                = 0x40; // offset
        inline constexpr uintptr_t RawImage_UVRect                  = 0xE8; // offset
        inline constexpr uintptr_t SR_ContentBounds                 = 0x90; // offset
        inline constexpr uintptr_t SR_ViewBounds                    = 0xA8; // offset
    }

    // (verbatim) AutoTurret
    namespace AutoTurret
    {
        inline constexpr uintptr_t authorizedPlayers                = 0x418; // offset
        inline constexpr uintptr_t muzzlePos                        = 0x4A0; // offset
        inline constexpr uintptr_t gun_yaw                          = 0x4B8; // offset
        inline constexpr uintptr_t lastYaw                          = 0x430; // offset
        inline constexpr uintptr_t lastYawRotation                  = 0x430; // offset
        inline constexpr uintptr_t gun_pitch                        = 0x4C0; // offset
        inline constexpr uintptr_t sightRange                       = 0x4C8; // offset
    }

    // (verbatim) patrolhelicopter
    namespace patrolhelicopter
    {
        inline constexpr uintptr_t weakspots                        = 0x2C0; // offset
        inline constexpr uintptr_t rotorPivot                       = 0x2C8; // offset
        inline constexpr uintptr_t mainRotor                        = 0x2D0; // offset
        inline constexpr uintptr_t tailRotor                        = 0x2E8; // offset
        inline constexpr uintptr_t rocket_tube_left                 = 0x300; // offset
        inline constexpr uintptr_t rocket_tube_right                = 0x308; // offset
        inline constexpr uintptr_t left_gun_yaw                     = 0x310; // offset
        inline constexpr uintptr_t left_gun_pitch                   = 0x318; // offset
        inline constexpr uintptr_t spotlightTarget                  = 0x3F0; // offset
        inline constexpr uintptr_t myAI                             = 0x3C0; // offset
    }

    // (verbatim) bradleyapc
    namespace bradleyapc
    {
        inline constexpr uintptr_t viewDistance                     = 0x3B4; // offset
        inline constexpr uintptr_t searchRange                      = 0x3B8; // offset
        inline constexpr uintptr_t engineSound                      = 0x2C0; // offset
        inline constexpr uintptr_t chasisLurchAngleDelta            = 0x308; // offset
        inline constexpr uintptr_t chasisLurchSpeedDelta            = 0x30C; // offset
    }

    // (verbatim) local_player_static
    namespace local_player_static
    {
        inline constexpr uintptr_t local_player                     = 0xFCB2720; // offset
        inline constexpr uintptr_t static_fields                    = 0xB8; // offset
        inline constexpr uintptr_t entity                           = 0x8; // offset
        inline constexpr uintptr_t hv_in_wrapper                    = 0x0; // offset
        inline constexpr uintptr_t is_wrapped                       = 0x1; // offset
    }

    // (verbatim) magazine
    namespace magazine
    {
        inline constexpr uintptr_t capacity                         = 0x18; // offset
        inline constexpr uintptr_t contents                         = 0x1C; // offset
        inline constexpr uintptr_t ammoType                         = 0x20; // offset
        inline constexpr uintptr_t definition                       = 0x10; // offset
    }

    // (verbatim) flameturret
    namespace flameturret
    {
        inline constexpr uintptr_t upper                            = 0x398; // offset
        inline constexpr uintptr_t arc                              = 0x3A0; // offset
        inline constexpr uintptr_t triggeredDuration                = 0x3A4; // offset
        inline constexpr uintptr_t flameRange                       = 0x3A8; // offset
        inline constexpr uintptr_t flameRadius                      = 0x3AC; // offset
        inline constexpr uintptr_t fuelPerSec                       = 0x3B0; // offset
        inline constexpr uintptr_t eyeTransform                     = 0x3B8; // offset
        inline constexpr uintptr_t damagePerSec                     = 0x3C0; // offset
        inline constexpr uintptr_t trigger                          = 0x3E0; // offset
    }

    // (verbatim) guntrap
    namespace guntrap
    {
        inline constexpr uintptr_t gunfireeffect                    = 0x398; // offset
        inline constexpr uintptr_t bulletEffect                     = 0x3A0; // offset
        inline constexpr uintptr_t triggeredEffect                  = 0x3A8; // offset
        inline constexpr uintptr_t muzzlePos                        = 0x3B0; // offset
        inline constexpr uintptr_t eyeTransform                     = 0x3B8; // offset
        inline constexpr uintptr_t numPellets                       = 0x3C0; // offset
        inline constexpr uintptr_t aimCone                          = 0x3C4; // offset
        inline constexpr uintptr_t sensorRadius                     = 0x3C8; // offset
        inline constexpr uintptr_t ammoType                         = 0x3D0; // offset
        inline constexpr uintptr_t trigger                          = 0x3D8; // offset
    }

    // (verbatim) BaseLauncher
    namespace BaseLauncher
    {
        inline constexpr uintptr_t initialSpeedMultiplier           = 0x4A8; // offset
    }

    // (verbatim) StorageContainer
    namespace StorageContainer
    {
        inline constexpr uintptr_t inventorySlots                   = 0x310; // offset
        inline constexpr uintptr_t panelName                        = 0x320; // offset
        inline constexpr uintptr_t panelTitle                       = 0x328; // offset
        inline constexpr uintptr_t isLootable                       = 0x31D; // offset
        inline constexpr uintptr_t isLockable                       = 0x31E; // offset
        inline constexpr uintptr_t isMonitorable                    = 0x31F; // offset
        inline constexpr uintptr_t dropsLoot                        = 0x314; // offset
        inline constexpr uintptr_t dropLootDestroyPercent           = 0x318; // offset
        inline constexpr uintptr_t allowedContents                  = 0x330; // offset
        inline constexpr uintptr_t allowedItem                      = 0x338; // offset
        inline constexpr uintptr_t maxStackSize                     = 0x358; // offset
        inline constexpr uintptr_t needsBuildingPrivilegeToUse      = 0x35C; // offset
        inline constexpr uintptr_t onlyAcceptCategory               = 0x388; // offset
        inline constexpr uintptr_t onlyOneUser                      = 0x38C; // offset
        inline constexpr uintptr_t dropPosition                     = 0x370; // offset
        inline constexpr uintptr_t dropVelocity                     = 0x37C; // offset
    }

    // (verbatim) LootContainer
    namespace LootContainer
    {
        inline constexpr uintptr_t destroyOnEmpty                   = 0x398; // offset
        inline constexpr uintptr_t lootDefinition                   = 0x3A0; // offset
        inline constexpr uintptr_t maxDefinitionsToSpawn            = 0x3A8; // offset
        inline constexpr uintptr_t minSecondsBetweenRefresh         = 0x3AC; // offset
        inline constexpr uintptr_t maxSecondsBetweenRefresh         = 0x3B0; // offset
        inline constexpr uintptr_t initialLootSpawn                 = 0x3B4; // offset
        inline constexpr uintptr_t xpLootedScale                    = 0x3B8; // offset
        inline constexpr uintptr_t scrapAmount                      = 0x3C4; // offset
        inline constexpr uintptr_t LootSpawnSlots                   = 0x3D0; // offset
        inline constexpr uintptr_t SpawnType                        = 0x3D8; // offset
        inline constexpr uintptr_t clanScoreEventForFirstLooter     = 0x3DC; // offset
    }

    // (verbatim) OreResourceEntity
    namespace OreResourceEntity
    {
        inline constexpr uintptr_t bonusPrefab                      = 0x248; // offset
        inline constexpr uintptr_t finishEffect                     = 0x250; // offset
        inline constexpr uintptr_t bonusFailEffect                  = 0x258; // offset
        inline constexpr uintptr_t useHotspotMinigame               = 0x260; // offset
        inline constexpr uintptr_t bonusSound                       = 0x268; // offset
        inline constexpr uintptr_t heightOffset                     = 0x270; // offset
    }

    // (verbatim) ResourceEntity
    namespace ResourceEntity
    {
        inline constexpr uintptr_t startHealth                      = 0x1F0; // offset
        inline constexpr uintptr_t baseProtection                   = 0x1F8; // offset
        inline constexpr uintptr_t skipDecorComponents              = 0x204; // offset
    }

    // (verbatim) CollectibleEntity
    namespace CollectibleEntity
    {
        inline constexpr uintptr_t itemName                         = 0x1F0; // offset
        inline constexpr uintptr_t itemList                         = 0x1F8; // offset
        inline constexpr uintptr_t pickupEffect                     = 0x200; // offset
        inline constexpr uintptr_t xpScale                          = 0x208; // offset
        inline constexpr uintptr_t suppressGatherRateMultiplier     = 0x20C; // offset
    }

    // (verbatim) GrowableEntity
    namespace GrowableEntity
    {
        inline constexpr uintptr_t Properties                       = 0x338; // offset
        inline constexpr uintptr_t SourceItemDef                    = 0x340; // offset
        inline constexpr uintptr_t state                            = 0x348; // offset
        inline constexpr uintptr_t plantSkin                        = 0x2D8; // offset
    }

    // (verbatim) PlayerCorpse
    namespace PlayerCorpse
    {
        inline constexpr uintptr_t playerName                       = 0x310; // offset
        inline constexpr uintptr_t playerSteamID                    = 0x308; // offset
        inline constexpr uintptr_t clientClothing                   = 0x340; // offset
    }

    // (verbatim) LootableCorpse
    namespace LootableCorpse
    {
        inline constexpr uintptr_t playerSteamID                    = 0x308; // offset
        inline constexpr uintptr_t _playerName                      = 0x310; // offset
    }

    // (verbatim) HackableLockedCrate
    namespace HackableLockedCrate
    {
        inline constexpr uintptr_t hackSeconds                      = 0x400; // offset
        inline constexpr uintptr_t timerText                        = 0x3F0; // offset
    }

    // (verbatim) HeldEntity
    namespace HeldEntity
    {
        inline constexpr uintptr_t viewModel                        = 0x2C8; // offset
        inline constexpr uintptr_t worldModelAnimation              = 0x208; // offset
        inline constexpr uintptr_t handBone                         = 0x250; // offset
        inline constexpr uintptr_t holdInfo                         = 0x260; // offset
        inline constexpr uintptr_t isBuildingTool                   = 0x27C; // offset
        inline constexpr uintptr_t forcedOwner                      = 0x280; // offset
        inline constexpr uintptr_t hostileScore                     = 0x29C; // offset
        inline constexpr uintptr_t itemOwner                        = 0x1F0; // offset
        inline constexpr uintptr_t ownerItemUID                     = 0x2D0; // offset
        inline constexpr uintptr_t viewModel_wrapper_kind           = 0x4; // offset
        inline constexpr uintptr_t viewModel_inner_off              = 0x28; // offset
        inline constexpr uintptr_t _punches                         = 0x240; // offset
    }

    // (verbatim) ItemIcon
    namespace ItemIcon
    {
        inline constexpr uintptr_t item_icon_c                      = 0xFC0CFA0; // offset
        inline constexpr uintptr_t type_info                        = 0xFC0CFA0; // offset
        inline constexpr uintptr_t static_fields                    = 0xB8; // offset
        inline constexpr uintptr_t containerLootStartTimes          = 0x0; // offset
        inline constexpr uintptr_t TryToMove                        = 0x0; // offset
        inline constexpr uintptr_t RunTimedAction                   = 0x0; // offset
        inline constexpr uintptr_t backgroundImage                  = 0xE8; // offset
    }

    // (verbatim) Dictionary
    namespace Dictionary
    {
        inline constexpr uintptr_t entries                          = 0x18; // offset
        inline constexpr uintptr_t count                            = 0x20; // offset
    }

    // (verbatim) DictionaryEntryArray
    namespace DictionaryEntryArray
    {
        inline constexpr uintptr_t length                           = 0x18; // offset
        inline constexpr uintptr_t data                             = 0x20; // offset
        inline constexpr uintptr_t hashCode                         = 0x0; // offset
        inline constexpr uintptr_t key                              = 0x8; // offset
        inline constexpr uintptr_t value                            = 0x10; // offset
        inline constexpr uintptr_t stride                           = 0x18; // offset
    }

    // (verbatim) ViewModel
    namespace ViewModel
    {
        inline constexpr uintptr_t instance                         = 0x28; // offset
        inline constexpr uintptr_t viewmodel_instance               = 0x28; // offset
    }

    // (verbatim) BaseViewModel
    namespace BaseViewModel
    {
        inline constexpr uintptr_t useViewModelCamera               = 0x40; // offset
        inline constexpr uintptr_t model                            = 0xC0; // offset
        inline constexpr uintptr_t bob                              = 0x108; // offset
        inline constexpr uintptr_t lower                            = 0xA0; // offset
        inline constexpr uintptr_t sway                             = 0x100; // offset
        inline constexpr uintptr_t ironSights                       = 0xB0; // offset
    }

    // (verbatim) EffectNetwork
    namespace EffectNetwork
    {
        inline constexpr uintptr_t type_info                        = 0x100DD1F0; // offset
        inline constexpr uintptr_t static_type_info                 = 0xFC83208; // offset
        inline constexpr uintptr_t static_fields                    = 0xB8; // offset
        inline constexpr uintptr_t instance                         = 0x8; // offset
        inline constexpr uintptr_t hitPosition                      = 0x98; // offset
    }

    // (verbatim) singleton_typeinfos
    namespace singleton_typeinfos
    {
        inline constexpr uintptr_t SingletonComponent_UI_LoadingScreen = 0xFBBB658; // offset
        inline constexpr uintptr_t SingletonComponent_MixerSnapshotManager = 0xFC14FA0; // offset
    }

    // (verbatim) TOD_Sky_Static
    namespace TOD_Sky_Static
    {
        inline constexpr uintptr_t tod_sky_c                        = 0xFC45770; // offset
        inline constexpr uintptr_t static_fields                    = 0xB8; // offset
        inline constexpr uintptr_t instances                        = 0x30; // offset
        inline constexpr uintptr_t instancesView                    = 0x30; // offset
        inline constexpr uintptr_t listItems                        = 0x10; // offset
        inline constexpr uintptr_t listSize                         = 0x18; // offset
        inline constexpr uintptr_t arrayData                        = 0x20; // offset
    }

    // (verbatim) TOD_CycleParameters
    namespace TOD_CycleParameters
    {
        inline constexpr uintptr_t Hour                             = 0x10; // offset
        inline constexpr uintptr_t Day                              = 0x14; // offset
        inline constexpr uintptr_t Month                            = 0x18; // offset
        inline constexpr uintptr_t Year                             = 0x1C; // offset
    }

    // (verbatim) unity_transform_native
    namespace unity_transform_native
    {
        inline constexpr uintptr_t access_struct_off                = 0x28; // offset
    }

    // (verbatim) transform_data
    namespace transform_data
    {
        inline constexpr uintptr_t pos_base_off                     = 0x18; // offset
        inline constexpr uintptr_t indices_b_off                    = 0x20; // offset
        inline constexpr uintptr_t root_pos_off                     = 0x90; // offset
        inline constexpr uintptr_t root_quat_off                    = 0xA0; // offset
        inline constexpr uintptr_t matrix_stride                    = 0x30; // offset
        inline constexpr uintptr_t walker_max_depth                 = 0x10; // offset
        inline constexpr uintptr_t slot_pad_off                     = 0xC; // offset
        inline constexpr uintptr_t slot_quat_off                    = 0x10; // offset
        inline constexpr uintptr_t slot_scale_off                   = 0x20; // offset
        inline constexpr uintptr_t slot_pos_quat_size               = 0x20; // offset
    }

    // (verbatim) unity_component
    namespace unity_component
    {
        inline constexpr uintptr_t game_object                      = 0x20; // offset
    }

    // (verbatim) unity_game_object
    namespace unity_game_object
    {
        inline constexpr uintptr_t components                       = 0x20; // offset
        inline constexpr uintptr_t component_count                  = 0x30; // offset
        inline constexpr uintptr_t component_stride                 = 0x10; // offset
        inline constexpr uintptr_t component_ptr_in_entry           = 0x8; // offset
        inline constexpr uintptr_t component_handle_in_native       = 0x18; // offset
    }

    // (verbatim) unity_transform
    namespace unity_transform
    {
        inline constexpr uintptr_t indirect_ptr_off                 = 0x28; // offset
        inline constexpr uintptr_t world_pos_off                    = 0x90; // offset
    }

    // (verbatim) unity_string
    namespace unity_string
    {
        inline constexpr uintptr_t m_stringLength                   = 0x10; // offset
        inline constexpr uintptr_t first_char                       = 0x14; // offset
    }

    // (verbatim) system_list
    namespace system_list
    {
        inline constexpr uintptr_t array                            = 0x10; // offset
        inline constexpr uintptr_t size                             = 0x18; // offset
        inline constexpr uintptr_t array_first_element              = 0x20; // offset
    }

    // (verbatim) convar_graphics
    namespace convar_graphics
    {
        inline constexpr uintptr_t convar_graphics                  = 0xFC1C9C0; // offset
        inline constexpr uintptr_t convar_graphics_instance         = 0xB8; // offset
        inline constexpr uintptr_t fov                              = 0xF0; // offset
    }

    // (verbatim) convar_admin
    namespace convar_admin
    {
        inline constexpr uintptr_t convar_admin                     = 0xFCA4BE0; // offset
        inline constexpr uintptr_t playerIds                        = 0x20; // offset
    }

} // namespace offsets
