// Auto-generated by Il2CppDumper. Do not edit.
// Filtered by parse-class — 147 entries requested.
//
// Field offsets are byte offsets inside the object (instance) or inside
// the class' static_fields block (static). Each field line ends with the
// C# type of that field — the key aid on obfuscated builds.
//
// type_info is 0x0 on this build (IL2CPP v27+ per-image usage tables not parsed).

#pragma once
#include <cstdint>

namespace offsets
{
    inline constexpr uintptr_t il2cpp_handle = 0x0;

    inline constexpr uintptr_t main_camera                      = camera; // namespace_alias
    inline constexpr uintptr_t received_data_from_server        = 0x27D3800; // offset

    // BaseEntity  (TypeDefIndex: 354)
    namespace base_entity
    {
        // instance fields
        inline constexpr uintptr_t model                            = 0x1A8; // Model
        inline constexpr uintptr_t flags                            = 0x1B0; // BaseEntity.Flags
    }

    // SkinnedMultiMesh  (TypeDefIndex: 1531)
    namespace skinned_multi_mesh
    {
    }

    // BaseCombatEntity  (TypeDefIndex: 1848)
    namespace base_combat_entity
    {
        // instance fields
        inline constexpr uintptr_t lifestate                        = 0x298; // BaseCombatEntity.LifeState
    }

    // BaseNetworkable  (TypeDefIndex: 2735)
    namespace base_networkable
    {
        inline constexpr uintptr_t type_info      = 0x0;  // TODO: not exposed on this build
        inline constexpr uintptr_t static_fields  = 0xB8;
        inline constexpr uintptr_t parent_statics = 0x10;
        inline constexpr uintptr_t wrapper_class  = 0x8;
    }

    // WorldItem  (TypeDefIndex: 3430)
    namespace world_item
    {
    }

    // PlayerEyes  (TypeDefIndex: 3445)
    namespace player_eyes
    {
    }

    // Model  (TypeDefIndex: 4973)
    namespace model
    {
    }

    // PlayerInventory  (TypeDefIndex: 5034)
    namespace player_inventory
    {
        inline constexpr uintptr_t main_container                   = container1; // alias
        inline constexpr uintptr_t belt                             = container2; // alias
        inline constexpr uintptr_t wear                             = container3; // alias
    }

    // BasePlayer  (TypeDefIndex: 5761)
    namespace base_player
    {
        inline constexpr uintptr_t cl_active_item                   = active_item; // alias
    }

    // PlayerInput  (TypeDefIndex: 5803)
    namespace player_input
    {
    }

    // RecoilProperties  (TypeDefIndex: 6578)
    namespace recoil_properties
    {
    }

    // CameraUpdateHook  (TypeDefIndex: 7665)
    namespace camera_update_hook
    {
    }

    // BaseProjectile  (TypeDefIndex: 7726)
    namespace base_projectile
    {
        // instance fields
        inline constexpr uintptr_t automatic                        = 0x380; // bool
        inline constexpr uintptr_t recoil                           = 0x3F0; // RecoilProperties
        inline constexpr uintptr_t projectile_vel_scale             = damage_scale; // alias
    }

    // PlayerModel  (TypeDefIndex: 8223)
    namespace player_model
    {
    }

    // BaseViewModel  (TypeDefIndex: 8308)
    namespace base_view_model
    {
        inline constexpr uintptr_t viewmodel_lower                  = viewmodel_type; // alias
        inline constexpr uintptr_t viewmodel_bob                    = muzzle_point; // alias
        inline constexpr uintptr_t viewmodel_sway                   = animation_events; // alias
    }

    // ItemDefinition  (TypeDefIndex: 8669)
    namespace item_definition
    {
        // instance fields
        inline constexpr uintptr_t category                         = 0x58; // ItemCategory
    }

    // TOD_Sky  (TypeDefIndex: 12555)
    namespace tod_sky
    {
        inline constexpr uintptr_t type_info      = 0x0;  // TODO: not exposed on this build
        inline constexpr uintptr_t static_fields  = 0xB8;
        // instance fields
        inline constexpr uintptr_t cycle                            = 0x40; // TOD_CycleParameters
        inline constexpr uintptr_t world                            = 0x48; // TOD_WorldParameters
        inline constexpr uintptr_t atmosphere                       = 0x50; // TOD_AtmosphereParameters
        inline constexpr uintptr_t day                              = 0x58; // TOD_DayParameters
        inline constexpr uintptr_t night                            = 0x60; // TOD_NightParameters
        inline constexpr uintptr_t sun                              = 0x68; // TOD_SunParameters
        inline constexpr uintptr_t moon                             = 0x70; // TOD_MoonParameters
        inline constexpr uintptr_t stars                            = 0x78; // TOD_StarParameters
        inline constexpr uintptr_t clouds                           = 0x80; // TOD_CloudParameters
        inline constexpr uintptr_t light                            = 0x88; // TOD_LightParameters
        inline constexpr uintptr_t fog                              = 0x90; // TOD_FogParameters
        inline constexpr uintptr_t ambient                          = 0x98; // TOD_AmbientParameters
        inline constexpr uintptr_t reflection                       = 0xA0; // TOD_ReflectionParameters
    }

    // Action  (TypeDefIndex: 13028)
    namespace action
    {
    }

    // Camera  (TypeDefIndex: 18280)
    namespace camera
    {
        inline constexpr uintptr_t type_info      = 0x0;  // TODO: not exposed on this build
        inline constexpr uintptr_t static_fields  = 0xB8;
    }

    // SkinnedMeshRenderer  (TypeDefIndex: 18398)
    namespace skinned_mesh_renderer
    {
    }

    // Transform  (TypeDefIndex: 18610)
    namespace transform
    {
    }

    // (verbatim) list_component_playermodel
    namespace list_component_playermodel
    {
        inline constexpr uintptr_t type_info                        = 0xFCE8520; // offset
        inline constexpr uintptr_t static_fields                    = 0xB8; // offset
        inline constexpr uintptr_t instance                         = 0x8; // offset
        inline constexpr uintptr_t parent                           = 0x10; // offset
        inline constexpr uintptr_t buffer                           = 0x10; // offset
        inline constexpr uintptr_t size                             = 0x18; // offset
    }

    // (verbatim) base_view_model_cctor
    namespace base_view_model_cctor
    {
        inline constexpr uintptr_t type_info                        = 0xFD06708; // offset
    }

    // (verbatim) model_state
    namespace model_state
    {
        inline constexpr uintptr_t flags                            = 0x40; // offset
    }

    // (verbatim) item_container
    namespace item_container
    {
        inline constexpr uintptr_t list                             = 0x28; // offset
        inline constexpr uintptr_t item_list                        = 0x28; // offset
    }

    // (verbatim) item
    namespace item
    {
        inline constexpr uintptr_t item_definition                  = 0x70; // offset
        inline constexpr uintptr_t item_uid                         = 0x40; // offset
        inline constexpr uintptr_t item_uid2                        = 0xA0; // offset
        inline constexpr uintptr_t item_uid3                        = 0xD8; // offset
        inline constexpr uintptr_t item_uid4                        = 0xF0; // offset
        inline constexpr uintptr_t held_entity                      = 0x58; // offset
        inline constexpr uintptr_t held_entity2                     = 0x80; // offset
    }

    // (verbatim) magazine
    namespace magazine
    {
        inline constexpr uintptr_t definition                       = 0x10; // offset
        inline constexpr uintptr_t capacity                         = 0x18; // offset
        inline constexpr uintptr_t contents                         = 0x1C; // offset
        inline constexpr uintptr_t ammo_type                        = 0x20; // offset
    }

    // (verbatim) flint_strike
    namespace flint_strike
    {
        inline constexpr uintptr_t success_frac                     = 0x488; // offset
        inline constexpr uintptr_t strike_recoil                    = 0x490; // offset
        inline constexpr uintptr_t spark_frame                      = 0x498; // offset
    }

    // (verbatim) native
    namespace native
    {
        inline constexpr uintptr_t cached_ptr                       = 0x10; // offset
        inline constexpr uintptr_t game_object                      = 0x30; // offset
        inline constexpr uintptr_t obj_transform                    = 0x8; // offset
    }

    // (verbatim) il2cpp_string
    namespace il2cpp_string
    {
        inline constexpr uintptr_t length                           = 0x10; // offset
        inline constexpr uintptr_t chars                            = 0x14; // offset
    }

    // (verbatim) il2cpp_list
    namespace il2cpp_list
    {
        inline constexpr uintptr_t items                            = 0x10; // offset
        inline constexpr uintptr_t count                            = 0x18; // offset
    }

    // (verbatim) il2cpp_array
    namespace il2cpp_array
    {
        inline constexpr uintptr_t max_length                       = 0x18; // offset
        inline constexpr uintptr_t first_element                    = 0x20; // offset
    }

    // (verbatim) il2cpp_class
    namespace il2cpp_class
    {
        inline constexpr uintptr_t name                             = 0x10; // offset
    }

} // namespace offsets
